javascript:(function(){var vdnUrl = ""; var paras = {videoCenterId: guid}; var vdnData = "pid=" + paras.videoCenterId + "&tai=ipad&client=html5"; if(isIPad()) { vdnData += "&im=1";} else{vdnData += "&im=0";}var vdn_tsp =new Date().getTime().toString().slice(0,10);var vdn_vn = "2049";var vdn_vc = "";var staticCheck = "47899B86370B879139C08EA3B5E88267";var vdn_uid = "";var vdn_wlan = "";if(typeof(getCookie_vdn)=="function"){if(!getCookie_vdn("Fingerprint")){if(typeof(getfingerprint)=="function" && typeof(getfingerprint)!="undefined" && !vodPlayerObjs.isFingerprintJsLoading){getfingerprint();}} else{vdn_uid = getCookie_vdn("Fingerprint");}}var vdn_vc = md5((vdn_tsp+vdn_vn+staticCheck+vdn_uid)).toUpperCase();vdnData += "&tsp="+vdn_tsp + "&vn="+ vdn_vn + "&vc="+vdn_vc + "&uid="+vdn_uid + "&wlan="+vdn_wlan;vdnUrl = vodUrlProtocol + "vdn.apps.cntv.cn/api/getHttpVideoInfo.do";var url = vdnUrl + "?" + vdnData; window.open(url);}());


javascript:(function(){var vdnUrl = ""; var paras = {videoCenterId: guid}; var vdnData = "pid=" + paras.videoCenterId + "&tai=ipad&client=html5"; if(isIPad()) { vdnData += "&im=1";} else{vdnData += "&im=0";}var vdn_tsp =new Date().getTime().toString().slice(0,10);var vdn_vn = "2049";var vdn_vc = "";var staticCheck = "47899B86370B879139C08EA3B5E88267";var vdn_uid = "";var vdn_wlan = "";if(typeof(getCookie_vdn)=="function"){if(!getCookie_vdn("Fingerprint")){if(typeof(getfingerprint)=="function" && typeof(getfingerprint)!="undefined" && !vodPlayerObjs.isFingerprintJsLoading){getfingerprint();}} else{vdn_uid = getCookie_vdn("Fingerprint");}}var vdn_vc = md5((vdn_tsp+vdn_vn+staticCheck+vdn_uid)).toUpperCase();vdnData += "&tsp="+vdn_tsp + "&vn="+ vdn_vn + "&vc="+vdn_vc + "&uid="+vdn_uid + "&wlan="+vdn_wlan;vdnUrl = vodUrlProtocol + "vdn.apps.cntv.cn/api/getHttpVideoInfo.do";var url = vdnUrl + "?" + vdnData; navigator.clipboard.writeText(url);alert('已成功将链接复制到剪贴板!');})();


javascript:(function() { var vdnUrl = ""; var paras = {videoCenterId: guid}; var vdnData = "pid=" + paras.videoCenterId + "&tai=ipad&client=html5"; if (isIPad()) { vdnData += "&im=1"; } else { vdnData += "&im=0"; } var vdn_tsp = new Date().getTime().toString().slice(0, 10); var vdn_vn = "2049"; var vdn_vc = ""; var staticCheck = "47899B86370B879139C08EA3B5E88267"; var vdn_uid = ""; var vdn_wlan = ""; if (typeof(getCookie_vdn) == "function") { if (!getCookie_vdn("Fingerprint")) { if (typeof(getfingerprint) == "function" && typeof(getfingerprint) != "undefined" && !vodPlayerObjs.isFingerprintJsLoading) { getfingerprint(); } } else { vdn_uid = getCookie_vdn("Fingerprint"); } } var vdn_vc = md5((vdn_tsp + vdn_vn + staticCheck + vdn_uid)).toUpperCase(); vdnData += "&tsp=" + vdn_tsp + "&vn=" + vdn_vn + "&vc=" + vdn_vc + "&uid=" + vdn_uid + "&wlan=" + vdn_wlan; vdnUrl = vodUrlProtocol + "vdn.apps.cntv.cn/api/getHttpVideoInfo.do"; copyToClipboard(vdnUrl + "?" + vdnData); })(); function copyToClipboard(text) { const element = document.createElement('textarea'); element.value = text; document.body.appendChild(element); element.select(); document.execCommand('copy'); document.body.removeChild(element); }



javascript:(function(){function getVideoUrl() { var vdnUrl = ""; var paras = { videoCenterId: guid }; var vdnData = "pid=" + paras.videoCenterId + "&tai=ipad&client=html5"; if (isIPad()) { vdnData += "&im=1"; } else { vdnData += "&im=0"; } var vdn_tsp = new Date().getTime().toString().slice(0,10); var vdn_vn = "2049"; var vdn_vc = ""; var staticCheck = "47899B86370B879139C08EA3B5E88267"; var vdn_uid = ""; var vdn_wlan = ""; if (typeof(getCookie_vdn) == "function") { if (!getCookie_vdn("Fingerprint")) { if (typeof(getfingerprint) == "function" && typeof(getfingerprint) != "undefined" && !vodPlayerObjs.isFingerprintJsLoading) { getfingerprint(); } } else { vdn_uid = getCookie_vdn("Fingerprint"); } } var vdn_vc = md5((vdn_tsp+vdn_vn+staticCheck+vdn_uid)).toUpperCase(); vdnData += "&tsp="+vdn_tsp + "&vn="+ vdn_vn + "&vc="+vdn_vc + "&uid="+vdn_uid + "&wlan="+vdn_wlan; vdnUrl = vodUrlProtocol + "vdn.apps.cntv.cn/api/getHttpVideoInfo.do"; return vdnUrl + "?" + vdnData;} const url = getVideoUrl(); fetch(url) .then(response => { if (response.ok) { return response.json(); } throw new Error('Network response was not ok.'); }) .then(data => { const videos = data.video.chapters4.map(item => item.url); const ws = new WebSocket('ws://localhost:6800/jsonrpc'); ws.onopen = function() { videos.forEach(url => { ws.send(`{ "jsonrpc": "2.0", "method": "aria2.addUri", "id": "1", "params": [ ["${url}"] ] }`); }); }; ws.onmessage = function(event) { console.log(event.data); }; }) .catch(error => { console.error('There has been a problem with your fetch operation:', error); });}());


